config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :environments, only: :index do
        resources :nodes, only: [], constraints: { id: /.+/ } do
          resources :keys, only: [:index, :show]
        end
      end
      resources :nodes, only: :index, constraints: { id: /.+/ } do
        resources :keys, only: [:index, :show]
      end
    end
  end

  resources :groups do
    resource :group_memberships, only: [:edit, :update]
  end

  resources :environments, only: :index do
    resources :layers, only: [] do
      resources :hierarchies, only: [] do
        resources :decrypted_values, only: [:create]

        resources :encrypted_values, only: [:create]
      end
    end

    resources :keys, only: [] do
      resources :files, only: [:index]
    end

    resources :nodes, only: :index, constraints: { id: /.+/ } do
      if Rails.configuration.hdm['read_only']
        resources :keys, only: [:index, :show] do
          resource :lookup, only: [:show]
        end
      else
        resources :keys, only: [:index, :show] do
          resources :layers, only: [] do
            resources :hierarchies, only: [] do
              resources :data_files, only: [] do
                resource :value, only: [:update, :destroy]
              end
            end
          end

          resource :lookup, only: [:show]
        end
      end
    end

    resource :tree, only: :show do
      resources :layers, only: [] do
        resources :hierarchies, only: [] do
          resources :paths, only: [], constraints: { id: /.+/ } do
            resource :tree_file, only: :show
          end
        end
      end
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resource :ldap_session, only: [:new, :create]
  resource :saml_session, only: [:new, :create]

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/initial_setup', to: 'page#initial_setup', as: :initial_setup

  root to: 'page#index'
end
# rubocop:enable Metrics/BlockLength

app/models/node.rb
class Node < HieraModel
  ENVIRONMENT_PRIORITY = %w[catalog_environment report_environment facts_environment].freeze

  attribute :hostname, :string
  attribute :environment
  alias name hostname

  def self.all
    node_records = PuppetDbClient.nodes
    environments = Environment.all.group_by(&:name)
    node_records.map do |node_record|
      env_name = node_record.values_at(*ENVIRONMENT_PRIORITY).compact.first
      env = environments[env_name].first
      new(hostname: node_record["certname"], environment: env)
    end
  end

  def self.find(hostname)
    all.find { |n| n.hostname == hostname }
  end

  def ==(other)
    other.is_a?(Node) &&
      hostname == other.hostname &&
      environment == other.environment
  end

  def facts
    @facts ||=
      PuppetDbClient.facts(certname: hostname)
  end

  def to_param
    hostname
  end

  def to_s
    hostname
  end
end

app/controllers/api/v1/nodes_controller.rb
module Api
  module V1
    class NodesController < Api::V1::ApiController
      def index
        @nodes = Node.all
        @nodes.select! { |n| current_user.may_access?(n) }

        respond_to do |format|
          format.json do
            render json: @nodes
          end
        end
      end
    end
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :load_environments

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Environments", :environments_path

  def index
    authorize! :index, Node
    @nodes = Node.all
    @nodes.select! { |n| current_user.may_access?(n) }

    add_breadcrumb @environment, environment_nodes_path(@environment)
  end
end

app/views/nodes/_info.html.erb
<div class="row my-3">
  <div class="col-12">
    <h1><%= @node.name %></h1>
  </div>
</div>

<% if Rails.configuration.hdm.node_info %>
  <div class="row my-3">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <% Rails.configuration.hdm.node_info[0..5].each_slice(2) do |facts| %>
              <div class="col-4">
                <dl>
                  <% facts.each do |fact| %>
                    <dt><%= fact %></dt>
                    <dd>
                      <% if value = @node.facts[fact.sub(/^facts\./, '')] %>
                        <%= value %>
                      <% else %>
                        <span class="text-body-tertiary">&lt;missing&gt;</span>
                      <% end %>
                    </dd>
                  <% end %>
                </dl>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/nodes/_select_node.html.erb
<%= form_tag "" do |form| %>
  <div class="form-group" data-controller="slim-select">
    <%= label_tag :node, "Select node" %>
    <div class="row">
      <div class="col-7">
        <select name="node" data-controller="select-navigation" data-action="change->select-navigation#navigate" data-slim-select-target="dropdown">
          <option value="" <% "selected" if @node.nil? %> data-url="<%= environment_nodes_path(@environment) %>"></option>
          <% @nodes.each do |node| %>
            <option data-url="<%= environment_node_keys_path(@environment, node) %>" <%= "selected" if node == @node %> <%= "data-hidable=\"true\"" if node.environment != @environment %>>
              <%= node.hostname %> (<%= node.environment %>)
            </option>
          <% end %>
        </select>
      </div>
      <div class="col-5">
        <div class="form-check form-switch">
          <input type="checkbox" checked class="form-check-input" id="node-filter" role="switch" data-action="change->slim-select#toggleFilter">
          <label class="form-check-label" for="node-filter">Only from selected environment</label>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/nodes/index.html.erb
<div class="row">
  <div class="col-6">
    <%= render "environments/select_environment" %>
  </div>
  <div class="col-6">
    <%= render "nodes/select_node" %>
    <%= render "files/search" %>
    <%= link_to "Show tree", environment_tree_path(@environment), class: "btn btn-secondary mt-2" %>
  </div>
</div>