config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :environments, only: :index do
        resources :nodes, only: [], constraints: { id: /.+/ } do
          resources :keys, only: [:index, :show]
        end
      end
      resources :nodes, only: :index, constraints: { id: /.+/ } do
        resources :keys, only: [:index, :show]
      end
    end
  end

  resources :groups do
    resource :group_memberships, only: [:edit, :update]
  end

  resources :environments, only: :index do
    resources :layers, only: [] do
      resources :hierarchies, only: [] do
        resources :decrypted_values, only: [:create]

        resources :encrypted_values, only: [:create]
      end
    end

    resources :keys, only: [] do
      resources :files, only: [:index]
    end

    resources :nodes, only: :index, constraints: { id: /.+/ } do
      if Rails.configuration.hdm['read_only']
        resources :keys, only: [:index, :show] do
          resource :lookup, only: [:show]
        end
      else
        resources :keys, only: [:index, :show] do
          resources :layers, only: [] do
            resources :hierarchies, only: [] do
              resources :data_files, only: [] do
                resource :value, only: [:update, :destroy]
              end
            end
          end

          resource :lookup, only: [:show]
        end
      end
    end

    resource :tree, only: :show do
      resources :layers, only: [] do
        resources :hierarchies, only: [] do
          resources :paths, only: [], constraints: { id: /.+/ } do
            resource :tree_file, only: :show
          end
        end
      end
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resource :ldap_session, only: [:new, :create]
  resource :saml_session, only: [:new, :create]

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/initial_setup', to: 'page#initial_setup', as: :initial_setup

  root to: 'page#index'
end
# rubocop:enable Metrics/BlockLength

app/models/group.rb
class Group < ApplicationRecord
  RESTRICTABLES = %w[environment node key].freeze

  serialize :rules, type: Array, coder: YAML

  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships

  validates :name, presence: true, uniqueness: true
  validates :restrict, inclusion: RESTRICTABLES
  validates :rules, regexp: true, length: { minimum: 1 }

  def destroyable?
    group_memberships.none?
  end

  def may_access?(record)
    record_class = record.class.name.downcase
    raise "Cannot check #{record_class}" unless record_class == restrict

    compiled_rules.any? { |r| r.match(record.name) }
  end

  private

  def compiled_rules
    @compiled_rules ||= rules.map { |r| Regexp.new(r) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  add_breadcrumb "Home", :root_path

  def index
    add_breadcrumb "Groups", :groups_path
    @groups = @groups.order(:name)
  end

  def show
    add_breadcrumb "Groups", :groups_path
    add_breadcrumb @group.name, group_path(@group)
  end

  def new
    add_breadcrumb "Groups", :groups_path
    add_breadcrumb "New Group", new_group_path
    @group = Group.new
  end

  def edit
    add_breadcrumb "Groups", :groups_path
    add_breadcrumb @group.name, group_path(@group)
    add_breadcrumb "Edit", edit_group_path(@group)
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: "Group was created successfully."
    else
      render action: "new"
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: "Group was updated successfully."
    else
      render action: "edit"
    end
  end

  def destroy
    @group.destroy

    redirect_to groups_path, notice: "Group was deleted successfully"
  end

  private

  def group_params
    permitted_params = params
                       .expect(group: [:name, :restrict, { rules: [] }])
    permitted_params[:rules] ||= []
    permitted_params
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h5><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h5>
      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-4">
    <%= form.label :name  %>
    <%= form.text_field :name, class:"form-control", autofocus: true %>
  </div>
  <fieldset>
    <legend>Access Control</legend>

    <p class="text-muted">
      You can restrict which environments, nodes or keys can be seen
      by members of this group.
      <br>
      Each restriction is a pattern (regular expression) that will be
      matched against the name of the environment/node/key.
      <br>
      Enter <code>.*</code> to allow everything.
      <br>
      To experiment with (ruby's) regular expressions, have a look at
      <%= link_to "https://rubular.com" do %>
        rubular.com <%= icon("box-arrow-up-right") %>
      <% end %>
    </p>

    <div class="mb-4">
      <%= form.label :restrict %>
      <%= form.select :restrict, Group::RESTRICTABLES, {}, class:"form-control" %>
    </div>
    <div class="mb-4" data-controller="append">
      <template data-append-target="template">
        <%= render "rule", rule: "" %>
      </template>
      <div data-append-target="container">
        <%= form.label :rules %>
        <% form.object.rules.each do |rule| %>
          <%= render "rule", rule: rule %>
        <% end %>
        <% if form.object.rules.none? %>
          <%= render "rule", rule: "" %>
        <% end %>
      </div>
      <%= button_tag type: 'button', class: "btn btn-primary", data: {action: "append#append"} do %>
        <%= icon("plus-circle") %> Add Rule
      <% end %>
    </div>
  </fieldset>

  <div class="actions">
    <%= form.button type: :submit, class:"btn btn-success min-width-btn" do %>
      <%= icon "save" %>
      Save
    <% end %>
  </div>
<% end %>

app/views/groups/_rule.html.erb
<div class="row mb-2" data-controller="remove">
  <div class="col-6">
    <%= text_field_tag "group[rules][]", rule, class:"form-control", readonly: local_assigns[:read_only] %>
  </div>
  <div class="col-4">
  </div>
  <div class="col-2">
    <% unless local_assigns[:read_only] %>
      <%= button_tag type: "button", class: "btn btn-danger", data: {action: "remove#remove"} do %>
        <%= icon "dash-circle" %> Remove Rule
      <% end %>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="container-fluid">
    <h1>Editing Group</h1>
    <%= render 'form', group: @group %>
    <br>
    <%= link_to @group, class:"btn btn-light min-width-btn" do %>
      <%= icon "eye" %>
      Show
    <% end %>
    <%= link_to groups_path, class:"btn btn-light min-width-btn" do %>
      <%= icon "arrow-left-short" %>
      Back
    <% end %>
</div>

app/views/groups/index.html.erb
<div class="container-fluid">
  <h1>Groups</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Restrict on</th>
        <th>Rules</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>
            <%= group.name %>
          </td>
          <td>
            <%= group.restrict %>
          </td>
          <td>
            <ul>
              <% group.rules.take(4).each do |rule| %>
                <li><%= rule %></li>
              <% end %>
              <% if group.rules.size > 4 %>
                <li>&ellipsis;</li>
              <% end %>
            </ul>
          </td>
          <td>
            <% if can? :show, group %>
              <%= link_to group, class:"btn btn-sm btn-light min-width-btn" do %>
                <%= icon "eye" %>
                Show
              <% end %>
            <% end %>
            <% if can? :edit, group %>
              <%= link_to edit_group_path(group), class:"btn btn-sm btn-primary min-width-btn" do %>
                <%= icon "pencil" %>
                Edit
              <% end %>
            <% end %>
            <% if group.destroyable? && can?(:delete, group) %>
              <%= link_to group, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"btn btn-sm btn-danger min-width-btn" do %>
                <%= icon "trash" %>
                Delete
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if can? :create, Group %>
    <br>
    <%= link_to new_group_path, class:"btn btn-success min-width-btn" do %>
      <%= icon "plus-circle" %>
      New Group
    <% end %>
  <% end %>
</div>

app/views/groups/new.html.erb
<div class="container-fluid">
  <h1>New Group</h1>

  <%= render 'form', group: @group %>

  <br>

  <%= link_to groups_path, class:"btn btn-light min-width-btn" do %>
    <%= icon "arrow-left-short" %>
    Back
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="container-fluid">
  <h1>Group Details</h1>
  <%= form_with(model: @group, local: true) do |form| %>
    <div class="mb-4">
      <%= form.label :name  %>
      <%= form.text_field :name, class:"form-control", readonly: true %>
    </div>
    <div class="mb-4">
      <%= form.label :restrict %>
      <%= form.text_field :restrict, class:"form-control", readonly: true %>
    </div>
    <div class="mb-4">
      <%= form.label :rules %>
      <% form.object.rules.each do |rule| %>
        <%= render "rule", rule: rule, read_only: true %>
      <% end %>
    </div>
  <% end %>
  <%= link_to edit_group_path(@group),class:"btn btn-primary min-width-btn" do %>
    <%= icon "pencil" %>
    Edit
  <% end %>
  <%= link_to groups_path,class:"btn btn-light min-width-btn" do %>
    <%= icon "arrow-left-short" %>
    Back
  <% end %>
  <h2 class="mt-4">Members</h2>

  <div class="row">
    <% @group.users.order(:username).in_groups(3) do |users| %>
      <div class="col-4">
        <ul>
          <% users.compact.each do |user| %>
            <li><%= link_to user.full_name_with_username, user %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <%= link_to edit_group_group_memberships_path(@group), class:"btn btn-primary min-width-btn" do %>
    <%= icon "pencil" %>
    Add/Remove Members
  <% end %>
</div>