config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :environments, only: :index do
        resources :nodes, only: [], constraints: { id: /.+/ } do
          resources :keys, only: [:index, :show]
        end
      end
      resources :nodes, only: :index, constraints: { id: /.+/ } do
        resources :keys, only: [:index, :show]
      end
    end
  end

  resources :groups do
    resource :group_memberships, only: [:edit, :update]
  end

  resources :environments, only: :index do
    resources :layers, only: [] do
      resources :hierarchies, only: [] do
        resources :decrypted_values, only: [:create]

        resources :encrypted_values, only: [:create]
      end
    end

    resources :keys, only: [] do
      resources :files, only: [:index]
    end

    resources :nodes, only: :index, constraints: { id: /.+/ } do
      if Rails.configuration.hdm['read_only']
        resources :keys, only: [:index, :show] do
          resource :lookup, only: [:show]
        end
      else
        resources :keys, only: [:index, :show] do
          resources :layers, only: [] do
            resources :hierarchies, only: [] do
              resources :data_files, only: [] do
                resource :value, only: [:update, :destroy]
              end
            end
          end

          resource :lookup, only: [:show]
        end
      end
    end

    resource :tree, only: :show do
      resources :layers, only: [] do
        resources :hierarchies, only: [] do
          resources :paths, only: [], constraints: { id: /.+/ } do
            resource :tree_file, only: :show
          end
        end
      end
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resource :ldap_session, only: [:new, :create]
  resource :saml_session, only: [:new, :create]

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/initial_setup', to: 'page#initial_setup', as: :initial_setup

  root to: 'page#index'
end
# rubocop:enable Metrics/BlockLength

app/views/shared/_auth_navigation.html.erb
<% if Ldap.configured? || Saml.configured? %>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "Local login", login_path, class: "nav-link #{"active" if local_assigns[:active] == :local}" %>
    </li>
    <% if Ldap.configured? %>
      <li class="nav-item">
        <%= link_to "LDAP login", new_ldap_session_path, class: "nav-link #{"active" if local_assigns[:active] == :ldap}" %>
      </li>
    <% end %>
    <% if Saml.configured? %>
      <li class="nav-item">
        <%= link_to new_saml_session_path, class: "nav-link" do %>
          <%= icon("box-arrow-up-right") %>
          SAML SSO login
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_diff.html.erb
<% split_diff = Diffy::SplitDiff.new(original_value, current_value, format: :html) %>
<table class="table">
  <thead>
    <tr>
      <th><%= @node.environment.name %></th>
      <th><%= @environment.name %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= raw(split_diff.left) %></td>
      <td><%= raw(split_diff.right) %></td>
    </tr>
  </tbody>
</table>

app/views/shared/_tabbed_diff.html.erb
<ul class="nav nav-tabs mb-2" role="tablist">
  <li class="nav-item" role="presentation">
    <button id="<%= "tab-value-#{dom_id}" %>" class="nav-link active" data-bs-target="<%= "#value-#{dom_id}" %>" data-bs-toggle="tab" type="button" role="tab" aria-controls="<%= "value-#{dom_id}" %>" aria-selected="true">Value</button>
  </li>
  <li class="nav-item" role="presentation">
    <button id="<%= "tab-diff-#{dom_id}" %>" class="nav-link" data-bs-target="<%= "#diff-#{dom_id}" %>" data-bs-toggle="tab" type="button" role="tab" aria-controls="<%= "diff-#{dom_id}" %>" aria-selected="false">Diff</button>
  </li>
</ul>

<div class="tab-content">
  <div id="<%= "value-#{dom_id}" %>" class="tab-pane fade show active" role="tabpanel" aria-labelledby="<%= "tab-value-#{dom_id}" %>">
    <%= yield %>
  </div>

  <div id="<%= "diff-#{dom_id}" %>" class="tab-pane fade" role="tabpanel" aria-labelledby="<%= "tab-diff-#{dom_id}" %>">
    <%= render "shared/diff", current_value:, original_value: %>
  </div>
</div>

app/views/shared/_top_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
  <div class="container">
    <a class="navbar-brand font-weight-bold" href="/">
      <%= image_tag "logo_full.png", alt: "HDM", height: "48" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
            <% if current_user.admin? %>
              (Admin)
            <% end %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if current_user %>
                <% if can? :update, current_user %>
                  <%= link_to edit_user_path(current_user), class: 'dropdown-item' do %>
                    <%= icon "person" %>
                    Edit Profile
                  <% end %>
                <% end %>
                <%= link_to logout_path, class: 'dropdown-item' do %>
                  <%= icon "box-arrow-right" %>
                  Logout
                <% end %>
              <% else %>
                <% if can? :create, User.new %>
                  <%= link_to "Sign up", signup_path, class: 'dropdown-item'  %>
                <% end %>
                <%= link_to "Login", login_path, class: 'dropdown-item'  %>
              <% end %>
              <% if User.accessible_by(current_ability).any? %>
                <div class="dropdown-divider"></div>
                <%= link_to users_path, class: 'dropdown-item' do %>
                  <%= icon "people" %>
                  List Users (<%= User.accessible_by(current_ability).count %>)
                <% end %>
                <% if can? :create, User.new %>
                  <%= link_to new_user_path, class: 'dropdown-item' do %>
                    <%= icon "person-plus" %>
                    Create a new User
                  <% end %>
                <% end %>
                <% if can? :show, Group %>
                  <%= link_to groups_path, class: "dropdown-item" do %>
                    <%= icon "person-badge" %>
                    List Groups
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to login_path, class: 'nav-link' do %>
              <%= icon "box-arrow-in-right" %>
              Login
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>