config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :environments, only: :index do
        resources :nodes, only: [], constraints: { id: /.+/ } do
          resources :keys, only: [:index, :show]
        end
      end
      resources :nodes, only: :index, constraints: { id: /.+/ } do
        resources :keys, only: [:index, :show]
      end
    end
  end

  resources :groups do
    resource :group_memberships, only: [:edit, :update]
  end

  resources :environments, only: :index do
    resources :layers, only: [] do
      resources :hierarchies, only: [] do
        resources :decrypted_values, only: [:create]

        resources :encrypted_values, only: [:create]
      end
    end

    resources :keys, only: [] do
      resources :files, only: [:index]
    end

    resources :nodes, only: :index, constraints: { id: /.+/ } do
      if Rails.configuration.hdm['read_only']
        resources :keys, only: [:index, :show] do
          resource :lookup, only: [:show]
        end
      else
        resources :keys, only: [:index, :show] do
          resources :layers, only: [] do
            resources :hierarchies, only: [] do
              resources :data_files, only: [] do
                resource :value, only: [:update, :destroy]
              end
            end
          end

          resource :lookup, only: [:show]
        end
      end
    end

    resource :tree, only: :show do
      resources :layers, only: [] do
        resources :hierarchies, only: [] do
          resources :paths, only: [], constraints: { id: /.+/ } do
            resource :tree_file, only: :show
          end
        end
      end
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resource :ldap_session, only: [:new, :create]
  resource :saml_session, only: [:new, :create]

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/initial_setup', to: 'page#initial_setup', as: :initial_setup

  root to: 'page#index'
end
# rubocop:enable Metrics/BlockLength

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :ensure_rbac_disabled
  before_action :load_environments

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Environments", :environments_path

  def show
    add_breadcrumb @environment, environment_nodes_path(@environment)
    add_breadcrumb "Tree"
  end
end

app/views/trees/_files.html.erb
<% @environment.layers.each do |layer| %>
  <div class="card mb-2">
    <div class="card-header"><%= layer.name_and_description %></div>
    <div class="card-body">
      <% layer.hierarchies.each do |hierarchy| %>
        <div class="list-group">
          <div class="list-group-item">
            <h2 class="list-group-header px-3 py-2">
              <span class="fs-6">
                <b><%= hierarchy.name %></b>
                <span class="badge bg-primary text-light"><%= hierarchy.backend %></span>
              </span>
            </h2>
          </div>
          <% hierarchy.candidate_files.each do |file| %>
            <%= link_to file.path, environment_tree_layer_hierarchy_path_tree_file_path(@environment, layer, hierarchy, file), class: "list-group-item list-group-item-action #{"active" if file == @data_file}" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/trees/show.html.erb
<div class="row">
  <div class="col-6">
    <%= render "environments/select_environment" %>
  </div>
  <div class="col-6">
  </div>
</div>

<div class="row mt-4">
  <div class="col-6">
    <%= render "files" %>
  </div>
  <div class="col-6">
  </div>
</div>